# necessary from inventory:
# vars:
#  storaccname   (storage account name)
#  storacckey
# any other variables noted in nodes.inv
# hostnames:
#  1master  (a single master node under that group name)
##############
--- # add necessary blocks to ocp nodes for storage from azure to hook up
- hosts: ocp-all
  gather_facts: no
  become: yes
  tasks:
  - name: "Add necessary Samba & CIFS packages to all nodes"
    yum:
      state: present
      update_cache: yes
      pkg: "{{ item }}"
    loop:
      - samba-client
      - samba-common
      - cifs-utils

  - name: set SELinux booleans on all nodes
    shell: "setsebool -P {{ item }} on"
    loop:
      - virt_use_samba
#      - virt_sandbox_use_samba
# Relevant BZ https://bugzilla.redhat.com/show_bug.cgi?id=1592727
#

- hosts: 1master
  gather_facts: smart
  become: no
  tasks:
  - name: save the base64 version of your storage account name
    shell: '/usr/bin/echo {{ storaccname }} | /usr/bin/base64'
    run_once: yes
    register: storaccname64

  - name: save the base64 version of your key as well
    shell: '/usr/bin/echo {{ storacckey }} | /usr/bin/base64'
    run_once: yes
    register: storacckey64

  - name: template out the secret file for azure file
    template:
      src: "az-file-secret.yml.j2"
      dest: "~/az-file-secret.yml"
      backup: yes
    run_once: true

  - name: template out the PV object definition
    template:
      src: "az-file-pv-def.yml.j2"
      dest: "~/az-file-pv-def.yml"
      backup: yes
    run_once: true

  - name: "create from that secret, one in OpenShift"
    shell: "oc create -f ~/az-file-secret.yml"
  
  - name: create from that PV object definition
    shell: "oc create -f ~/az-file-pv-def.yml"
    
  - name: notify to verify
    debug: msg="Please verify that both of the above creation tasks, created their items in OpenShift before consuming Azure File Storage"
