--- # add necessary blocks to ocp nodes for storage from azure to hook up
- hosts: ocp-all
  gather_facts: no
  become: yes
  tasks:
  - name: Make the Azure dir if not there on nodes
    file:
      path: /etc/azure
      state: directory
      mode: 0755
  - name: Copy your prepared `azure.conf` to all nodes
    copy:
      src: azure.conf
      dest: /etc/azure/azure.conf
      backup: yes
      force: yes
# change master config only on masters
- hosts: master
  gather_facts: no
  become: yes
  tasks:
  - name: add apiServerArguments block to master-config
    blockinfile:
      state: present
      path: /etc/origin/master/master-config.yaml
      backup: yes
      marker: "# -- {mark} ANSIBLE MANAGED BLOCK 1 of 2 --"
      insertafter: "apiServerArguments:"
      block: |2
            cloud-provider:
              - "azure"
            cloud-config:
              - "/etc/azure/azure.conf"
  - name: add controllerArguments block to master-config
    blockinfile:
      state: present
      path: /etc/origin/master/master-config.yaml
      backup: yes
      marker: "# -- {mark} ANSIBLE MANAGED BLOCK 2 of 2 --"
      insertafter: "controllerArguments:"
      block: |2
            cloud-provider:
              - "azure"
            cloud-config:
              - "/etc/azure/azure.conf"
# change node config on all nodes in cluster
- hosts: ocp-all
  gather_facts: no
  become: yes
  tasks:
  - name: add kubeletArguments to node config
    blockinfile:
      state: present
      path: /etc/origin/node/node-config.yaml
      backup: yes
      marker: "# -- {mark} ANSIBLE MANAGED BLOCK 1 of 1 --"
      insertafter: "kubeletArguments:"
      block: |2
          cloud-provider:
            - "azure"
          cloud-config:
            - "/etc/azure/azure.conf"
# restart master services
- hosts: master
  gather_facts: no
  become: yes
  serial: yes
  tasks:
  - name: restart openshift master services in series
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - atomic-openshift-master-api
      - atomic-openshift-master-controllers
#      - atomic-openshift-node
# restart non-master services
- hosts: ocp-all
  gather_facts: no
  become: yes
  #serial: yes
  tasks:
  - name: restart openshift node services in series
    service:
      name: atomic-openshift-node
      state: restarted
